# Generated by Django 3.2 on 2021-05-02 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionReusable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tab', models.CharField(choices=[('start', 'start'), ('portrety', 'portrety'), ('okolicznosciowe', 'okolicznosciowe'), ('rodzinne', 'rodzinne'), ('sensualne', 'sensualne'), ('wiecej', 'wiecej')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_theme', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reusable_photo')),
                ('column', models.CharField(choices=[('kolumna1', 'kolumna1'), ('kolumna2', 'kolumna2'), ('kolumna3', 'kolumna3')], max_length=20)),
                ('seat_number', models.CharField(max_length=40, unique=True)),
                ('site_tab', models.CharField(choices=[('start', 'start'), ('portrety', 'portrety'), ('okolicznosciowe', 'okolicznosciowe'), ('rodzinne', 'rodzinne'), ('sensualne', 'sensualne'), ('wiecej', 'wiecej')], max_length=30)),
                ('photo_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photographer.phototheme')),
            ],
        ),
    ]
