# Generated by Django 3.2 on 2021-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionreusable',
            old_name='tab',
            new_name='site_tab',
        ),
        migrations.AlterField(
            model_name='descriptionreusable',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionreusable',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
