# Generated by Django 3.2 on 2021-05-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_auto_20210502_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototheme',
            name='site_tab',
            field=models.CharField(blank=True, choices=[('start', 'start'), ('portrety', 'portrety'), ('okolicznosciowe', 'okolicznosciowe'), ('rodzinne', 'rodzinne'), ('sensualne', 'sensualne'), ('wiecej', 'wiecej')], max_length=20, null=True),
        ),
    ]
