# Generated by Django 3.2 on 2021-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_alter_phototheme_site_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoportfolio',
            name='seat_number',
            field=models.CharField(max_length=40),
        ),
    ]
