# Generated by Django 3.2 on 2021-05-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0005_alter_photoportfolio_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_text', models.TextField()),
                ('art_order', models.IntegerField()),
                ('art_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.articletitle')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_photo', models.ImageField(upload_to='blog_photo')),
                ('art_order', models.IntegerField()),
                ('art_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.articletitle')),
            ],
        ),
    ]
