# Generated by Django 3.2 on 2021-05-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0006_articleimage_articletext_articletitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_photo', models.ImageField(upload_to='blog_photo')),
                ('art_text', models.TextField()),
                ('art_order', models.IntegerField()),
                ('art_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.articletitle')),
            ],
        ),
        migrations.RemoveField(
            model_name='articletext',
            name='art_title',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='ArticleText',
        ),
    ]
