# Generated by Django 3.2 on 2021-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0007_auto_20210524_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=50)),
                ('art_photo', models.ImageField(upload_to='blog_photo')),
                ('art_text', models.TextField()),
            ],
        ),
    ]
