# Generated by Django 3.2 on 2021-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0008_firstarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebody',
            name='art_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo'),
        ),
        migrations.AlterField(
            model_name='articlebody',
            name='art_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
