# Generated by Django 3.2 on 2021-05-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0009_auto_20210526_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_photo', models.ImageField(blank=True, null=True, upload_to='blog_photo')),
                ('contact_title', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='firstarticle',
            name='art_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo'),
        ),
    ]
