# Generated by Django 3.2 on 2021-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0011_auto_20210530_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('facebook_name', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_name', models.CharField(blank=True, max_length=15, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
