# Generated by Django 3.2 on 2021-06-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0013_auto_20210619_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoportfolio',
            name='photo_theme',
        ),
    ]
