# Generated by Django 3.2 on 2021-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0014_remove_photoportfolio_photo_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoportfolio',
            name='seat_number',
            field=models.CharField(max_length=40),
        ),
    ]
