# Generated by Django 3.2 on 2021-06-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0017_alter_photoportfolio_photo_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoportfolio',
            name='photo_theme',
        ),
    ]
