# Generated by Django 3.2 on 2021-06-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0019_photoportfolio_photo_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoportfolio',
            name='column',
        ),
        migrations.RemoveField(
            model_name='photoportfolio',
            name='photo_theme',
        ),
        migrations.RemoveField(
            model_name='photoportfolio',
            name='seat_number',
        ),
    ]
