# Generated by Django 3.2 on 2021-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0020_auto_20210619_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoportfolio',
            name='seat_number',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
