# Generated by Django 3.2 on 2021-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0021_photoportfolio_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoportfolio',
            name='column',
            field=models.CharField(choices=[('kolumna1', 'kolumna1'), ('kolumna2', 'kolumna2'), ('kolumna3', 'kolumna3')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
