# Generated by Django 3.2 on 2021-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0023_photoportfolio_photo_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoportfolio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reusable_photo'),
        ),
    ]
