# Generated by Django 3.2 on 2021-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0027_alter_photoportfolio_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoportfolio',
            name='photo_theme',
            field=models.CharField(blank=True, help_text='Morze być puste', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PhotoTheme',
        ),
    ]
