# Generated by Django 3.2 on 2021-07-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0028_auto_20210626_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlebody',
            name='art_order',
        ),
    ]
