# Generated by Django 3.2 on 2021-07-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0029_remove_articlebody_art_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebody',
            name='art_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='photographer.articletitle'),
        ),
    ]
