# Generated by Django 3.2 on 2021-07-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0031_alter_articletitle_art_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebody',
            name='art_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='photographer.articletitle'),
        ),
    ]
