# Generated by Django 3.2 on 2021-07-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0033_alter_articlebody_art_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebody',
            name='art_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photographer.articletitle'),
        ),
    ]
