# Generated by Django 3.2 on 2021-07-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0039_auto_20210717_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactEmail',
        ),
    ]
