# Generated by Django 3.2 on 2021-07-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0040_delete_contactemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='normal_label',
            new_name='normal_text',
        ),
    ]
